@startuml
allowmixing
hide stereotypes
skinparam roundCorner 3
skinparam defaultFontName system-ui
skinparam ArrowColor #7A7A7A




rectangle "Welcome to Acme Bank" as n0 <<n0type>> 
hexagon "Are you an\nexisting\ncustomer?" as n1 <<n1type>> 


<style>

._Pattern {
    BackgroundColor gold
    LineColor #665600
}

._Critique {
    BackgroundColor khaki
    LineColor #867B12    
}

._Constraint {
    BackgroundColor mistyrose
    LineColor #C01300
}

._Success {
    BackgroundColor TECHNOLOGY
    LineColor #00B600
}

.n0type {
    LineColor #919129
    BackgroundColor beige
    
}
.n1type {
    LineColor #C68400
    BackgroundColor floralwhite
    
}
</style>

n0 -down-> n1




@enduml

