@startuml
allowmixing
hide stereotypes
skinparam roundCorner 3
skinparam defaultFontName system-ui
skinparam ArrowColor #7A7A7A


hide circle
hide methods


class "Project" as n0 <<n0type>>  {
    tasks:Task[*]
    lead:Person
} 
class "Task" as n1 <<n1type>>  {
    name:String
} 
class "Person" as n2 <<n2type>>  {
    name:String
} 


<style>

._Pattern {
    BackgroundColor gold
    LineColor #665600
}

._Critique {
    BackgroundColor khaki
    LineColor #867B12    
}

._Constraint {
    BackgroundColor mistyrose
    LineColor #C01300
}

._Success {
    BackgroundColor TECHNOLOGY
    LineColor #00B600
}

.n0type {
    LineColor #C68400
    BackgroundColor floralwhite
    
}
.n1type {
    LineColor #C68400
    BackgroundColor floralwhite
    
}
.n2type {
    LineColor #C68400
    BackgroundColor floralwhite
    
}
</style>


n0 -right-> n1: *
n0 -left-> n2



@enduml

