@startuml
allowmixing
hide stereotypes
skinparam roundCorner 3
skinparam defaultFontName system-ui
skinparam ArrowColor #7A7A7A




rectangle "ACME" as n0 <<n0type>>  {
    node "<<Task>>\nAnalysis" as n1 <<n1type>> 
    node "<<Task>>\nDesign" as n2 <<n2type>> 
    node "<<Task>>\nImplementation" as n3 <<n3type>> 
    cloud "Alice" as n4 <<n4type>> 
    cloud "Manager: Bob" as n5 <<n5type>> 
} 


<style>

._Pattern {
    BackgroundColor gold
    LineColor #665600
}

._Critique {
    BackgroundColor khaki
    LineColor #867B12    
}

._Constraint {
    BackgroundColor mistyrose
    LineColor #C01300
}

._Success {
    BackgroundColor TECHNOLOGY
    LineColor #00B600
}

.n0type {
    LineColor #00C6C6
    BackgroundColor azure
    
}
.n1type {
    LineColor #919129
    BackgroundColor beige
    
    fontColor green
}
.n2type {
    LineColor #919129
    BackgroundColor beige
    
    fontColor green
}
.n3type {
    LineColor #919129
    BackgroundColor beige
    
    fontColor green
}
.n4type {
    LineColor #00C6C6
    BackgroundColor azure
    
    fontColor magenta
    fontSize 20
}
.n5type {
    LineColor #003300
    BackgroundColor green
    
    fontColor white
    fontSize 20
}
</style>

n4 -[thickness=10]down-> n1
n5 -[thickness=10]down-> n2
n5 -[thickness=5]down-> n3: 50%
n4 -[thickness=5]down-> n3: 50%

n2 -[#red,dashed,thickness=2]down-> n4: leads



@enduml

