@startuml
hide stereotypes
skinparam roundCorner 3
skinparam defaultFontName system-ui
skinparam ArrowColor #7A7A7A





component "Not" as n0  <<n0type>> {
}
rectangle "in" as n1  <<n1type>> {
}

component "And" as n3  <<n3type>> {
}
rectangle "a" as n4  <<n4type>> {
}
rectangle "b" as n5  <<n5type>> {
}

component "Or" as n7  <<n7type>> {
}


rectangle "out" as n10  <<n10type>> {
}


<style>

._Pattern {
    BackgroundColor gold
    LineColor %darken("gold",60)
}

._Critique {
    BackgroundColor khaki
    LineColor %darken("khaki",60)    
}

._Constraint {
    BackgroundColor mistyrose
    LineColor %darken("mistyrose",60)
}

._Success {
    BackgroundColor TECHNOLOGY
    LineColor %darken("TECHNOLOGY",60)
}

.n0type {
    LineColor %darken("azure",60)
    BackgroundColor azure
    
    
    
    
    
}
.n1type {
    LineColor %darken("floralwhite",60)
    BackgroundColor floralwhite
    
    
    
    
    
}
.n3type {
    LineColor %darken("azure",60)
    BackgroundColor azure
    
    
    
    
    
}
.n4type {
    LineColor %darken("floralwhite",60)
    BackgroundColor floralwhite
    
    
    
    
    
}
.n5type {
    LineColor %darken("floralwhite",60)
    BackgroundColor floralwhite
    
    
    
    
    
}
.n7type {
    LineColor %darken("azure",60)
    BackgroundColor azure
    
    
    
    
    
}
.n10type {
    LineColor %darken("lemonchiffon",60)
    BackgroundColor lemonchiffon
    
    
    
    
    
}
</style>

n0 -down-> n7: out→a
n3 -down-> n7: out→b

n0 <-up- n1
n3 <-up- n4
n3 <-up- n5
n7 -down-> n10



@enduml

