@startuml
hide stereotypes
skinparam roundCorner 3
skinparam defaultFontName system-ui
skinparam ArrowColor #7A7A7A


hide circle
hide methods


class "Project" as n0 <<class>> <<n0type>> {
    tasks:Task[*]
}
class "Task" as n1 <<class>> <<n1type>> {
    name:String
}


<style>

._Pattern {
    BackgroundColor gold
    LineColor %darken("gold",60)
}

._Critique {
    BackgroundColor khaki
    LineColor %darken("khaki",60)    
}

._Constraint {
    BackgroundColor mistyrose
    LineColor %darken("mistyrose",60)
}

._Success {
    BackgroundColor TECHNOLOGY
    LineColor %darken("TECHNOLOGY",60)
}

.n0type {
    LineColor %darken("floralwhite",60)
    BackgroundColor floralwhite
    
}
.n1type {
    LineColor %darken("floralwhite",60)
    BackgroundColor floralwhite
    
}
</style>


n0 -right-> n1: *



@enduml

