@startuml
allowmixing
hide stereotypes
skinparam roundCorner 3
skinparam defaultFontName system-ui
skinparam ArrowColor #7A7A7A




rectangle "<img:https://plantuml.com/logo3.png>\neol" as n0 <<n0type>> 
rectangle "<img:https://plantuml.com/logo3.png>\netl" as n1 <<n1type>> 
rectangle "<img:https://plantuml.com/logo3.png>\nevl" as n2 <<n2type>> 
rectangle "<img:https://plantuml.com/logo3.png>\neml" as n3 <<n3type>> 


<style>

._Pattern {
    BackgroundColor gold
    LineColor %darken("gold",60)
}

._Critique {
    BackgroundColor khaki
    LineColor %darken("khaki",60)    
}

._Constraint {
    BackgroundColor mistyrose
    LineColor %darken("mistyrose",60)
}

._Success {
    BackgroundColor TECHNOLOGY
    LineColor %darken("TECHNOLOGY",60)
}

.n0type {
    LineColor white
    BackgroundColor white
    HorizontalAlignment center
}
.n1type {
    LineColor white
    BackgroundColor white
    HorizontalAlignment center
}
.n2type {
    LineColor white
    BackgroundColor white
    HorizontalAlignment center
}
.n3type {
    LineColor white
    BackgroundColor white
    HorizontalAlignment center
}
</style>


n1 -up-> n0
n2 -up-> n0
n3 -up-> n1



@enduml

