@startuml
hide stereotypes
skinparam roundCorner 3
skinparam defaultFontName system-ui
skinparam ArrowColor #7A7A7A





rectangle "A" as n0  <<n0type>> {
}
rectangle "B" as n1  <<n1type>> {
}
rectangle "C" as n2  <<n2type>> {
}


<style>

._Pattern {
    BackgroundColor gold
    LineColor %darken("gold",60)
}

._Critique {
    BackgroundColor khaki
    LineColor %darken("khaki",60)    
}

._Constraint {
    BackgroundColor mistyrose
    LineColor %darken("mistyrose",60)
}

._Success {
    BackgroundColor TECHNOLOGY
    LineColor %darken("TECHNOLOGY",60)
}

.n0type {
    LineColor %darken("beige",60)
    BackgroundColor beige
    
    
    
    
    
}
.n1type {
    LineColor %darken("beige",60)
    BackgroundColor beige
    
    
    
    
    
}
.n2type {
    LineColor %darken("beige",60)
    BackgroundColor beige
    
    
    
    
    
}
</style>

n0 -down-> n1
n1 -down-> n2
n0 -down-> n0
n2 -down-> n0




@enduml

