name: Pull requests

on:
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.9'
        distribution: 'graalvm'
    - name: Set up Node
      uses: actions/setup-node@v4.0.0
      with:
        node-version: '16.x'
    - name: Install Node dependencies
      run: npm ci
      working-directory: ./ep-tool-server
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b
    - name: Build with Gradle
      run: ./gradlew build
